apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: faqservice-autoscaler
  namespace: BharatFD
  labels:
    mylabel: faqservice
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: faqservice-deployment
  targetCPUUtilizationPercentage: 50