apiVersion: v1
kind: Service
metadata:
  name: faqservice-service
  namespace: BharatFD
spec:
  type: NodePort
  selector:
    mylabel: faqservice
  ports:
    - protocol: TCP
      nodePort: 30000  # Replace with the desired NodePort
      port: 8000
      targetPort: 8000